### ISSUE TITLE
🐛 [BUG] - Clicking links opens two tabs to the same URL

### ISSUE THREAD

**Issue by serkor1** [flaming-codes/crane-app#176]
### Description

For any package listed on on the website, if I click on the github-link it will open a new window to the repository, but at the same time it redirects the original site to the same link.

### Reproduction steps

```bash
1. Go to https://www.cran-e.com/package/tidyverse
2. Scroll down to `About`
3. Click on the github-link
```

### Browsers

Firefox

### OS

Windows

**Comment by flaming-codes** [comment]
Hi, many thanks for taking the time and reporting this issue.

- I'm able to reproduce this behaviour on Chromium browser
- Safari on macOS won't open a new tab and simply navigate to the new site in the same tab
